parameters:
  templates:
    libre:
      type: libre
      summary: Template Libre
      code: libre
      name: Libre
    newsletter_template:
      type: libre
      summary: Template Newsletter
      code: newsletter_template
      name: Template Newsletter
    contact:
      type: formulaire
      summary: Formulaire Contact
      code: contact
      name: Contact
    newsletter:
      type: formulaire
      summary: Formulaire Newsletter
      code: newsletter
      name: Newsletter
    livredor:
      type: formulaire
      summary: Formulaire Livre d'or
      code: livredor
      name: Livre d'or
    livredor1:
      type: livredor 
      summary: Livre d'or classique
      code: livredor1
      name: Livre d'or Classique
    folio1:
      type: liste 
      summary: Folio Classique
      code: folio1
      name: Folio Classique
    folio2:
      type: liste 
      summary: Folio effet survol (+)
      code: folio2
      name: Folio effet survol (+)
    folio3:
      type: liste 
      summary: Folio gallery
      code: folio3
      name:  Folio gallery
    folio4:
      type: liste 
      summary: Folio serré
      code: folio4
      name:  Folio serré
    folio5:
      type: liste 
      summary: Folio gallery 2
      code: folio5
      name:  Folio gallery 2
    folio_video1:
      type: liste 
      summary: Folio video classique
      code: folio_video1
      name: Folio video classique
    modale1:
      type: modale 
      summary: Présentation modale slide
      code: modale1
      name: Modale slide
    modale2:
      type: modale 
      summary: Présentation modale seule
      code: modale2
      name: Modale seule
    carousel1:
      type: liste 
      summary: Présentation carousel slide
      code: carousel1
      name: Carousel slide
    carousel2:
      type: liste 
      summary: Présentation carousel fade
      code: carousel2
      name: Carousel fade
    carousel3:
      type: liste 
      summary: Présentation carousel par groupe de 3 images
      code: carousel3
      name: Carousel par groupe de 3 images
    card1:
      type: liste 
      summary: Cartes affichée par 2 avec fichier à télécharger
      code: card1
      name: Cartes avec pdf à télécharger
    card2:
      type: liste 
      summary: Carte de présentation avec photo
      code: card2
      name: Carte de présentation avec photo
