# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
- { resource: 'hermes_templates.yaml'}
- { resource: 'hermes_configs.yaml'}
parameters:
  hermes_admin_email: '%env(APP_HERMES_ADMIN_EMAIL)%'
  hermes_admin_password: '%env(APP_HERMES_ADMIN_PASSWORD)%'
  hermes_newsletter_email: '%env(APP_HERMES_NEWSLETTER_EMAIL)%'
  version: v1.0.0
  app.locales: [fr, en] #'%env(APP_LOCALES)%'
  app.default_locale: '%env(APP_DEFAULT_LOCALE)%'
  app.name: '%env(APP_NAME)%'
  hermes_pages: '%env(APP_PAGES)%'
  hermes_list_templates: '%env(APP_LIST_TEMPLATES)%'
  hermes_list_type_image: '%env(APP_LIST_TYPE_IMAGE)%'
  hermes_database_dir: '%env(DATABASE_URL)%'
  hermes_database_config_dir: '%env(DATABASE_CONFIG_URL)%'
  hermes_path_content_image: '%env(APP_PATH_CONTENT_IMAGES)%'
  hermes_path_content_image_post: '%env(APP_PATH_CONTENT_IMAGES_POSTS)%'
  hermes_path_content_images: '%env(APP_PATH_CONTENT_IMAGES)%'
  hermes_path_cache_image: '%env(APP_PATH_CACHE_IMAGES)%'
  hermes_path_hermes_images: '%kernel.project_dir%/public/%env(APP_PATH_HERMES_IMAGES)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
